version: '3.8'
volumes:
  config: null
  monitor: null
services:
  asterisk:
    network_mode: host
    image: 'leucotron/asterisk:20.8.1'
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - './data/etc/asterisk:/data/etc/asterisk'      
      - './data/var/log/supervisor:/data/var/log/supervisor'
      - './data/var/log/asterisk:/data/var/log/asterisk'
      - './data/var/spool/asterisk:/data/var/spool/asterisk'
      - './data/var/lib/asterisk/sounds:/data/var/lib/asterisk/sounds'
      - './data/var/lib/asterisk/moh:/data/var/lib/asterisk/moh'          
    restart: unless-stopped
