#!/bin/bash
set -ex

create-volume

pidfile=/var/run/asterisk/asterisk.pid
command=/usr/sbin/asterisk

# Proxy signals
function kill_app(){
    #kill $(cat $pidfile)    
    $command -rx "core stop now"
    service fail2ban stop 
    exit $?
}
trap "kill_app" SIGINT SIGTERM

echo 'Force Fail2ban Sock remove'
FAIL2BAN_SOCK=/var/run/fail2ban/fail2ban.sock
rm -f $FAIL2BAN_SOCK || true

EXIT_CODE=0
echo 'Run Fail2ban'
service fail2ban start || EXIT_CODE=$?
echo $EXIT_CODE

# start asterisk
$command -f -U asterisk -G asterisk -vvvg -c
sleep 2

# Loop while the pidfile and the process exist
while [ -f $pidfile ] && kill -0 $(cat $pidfile) ; do
    sleep 5
done
exit 1000 # exit unexpected
